### ISSUE TITLE
Why does repeatedly registering `server_socket` to the event loop enable multiple connections to clients?

### ISSUE THREAD

**Issue by YconquestY** [luminousmen/grokking_concurrency#2]
I noted a big fix https://github.com/luminousmen/grokking_concurrency/commit/667d37e16e3ab2b4bada0f75af38b26df607290f added the following snippet to method `_on_accept` of class `Server`:

https://github.com/luminousmen/grokking_concurrency/blob/667d37e16e3ab2b4bada0f75af38b26df607290f/Chapter%2011/pizza_reactor.py#L83-L84

Basically, the snippet re-register `server_socket` in the event loop **every time** a new connection is established with a client. As https://github.com/luminousmen/grokking_concurrency/commit/667d37e16e3ab2b4bada0f75af38b26df607290f said, the server cannot connect multiple clients without re-registration. In contrast, [`_on_read`](https://github.com/luminousmen/grokking_concurrency/blob/667d37e16e3ab2b4bada0f75af38b26df607290f/Chapter%2011/pizza_reactor.py#L86-L102) and [`_on_write`](https://github.com/luminousmen/grokking_concurrency/blob/667d37e16e3ab2b4bada0f75af38b26df607290f/Chapter%2011/pizza_reactor.py#L104-L118) handlers do **not** re-register sockets, but a client may send messages to the server multiple times.

What makes `server_socket` different so that we must re-register it to enble multiple connections to clients?

**Comment by luminousmen** [comment]
The difference between `server_socket` and client sockets (handled by _on_read and _on_write) in terms of re-registration in the event loop is from their distinct roles and behaviors in the app.

After accepting a connection and handling the initial connection setup (e.g., making the socket non-blocking, setting up initial event registration for the newly connected client), the `server_socket` needs to be ready to accept more incoming connections. However, once an accept call is made on the `server_socket`, it is temporarily removed from the set of sockets being polled for incoming connections. 

Re-registering the `server_socket` with the event loop for `POLLIN` events ensures that it continues to listen for new connection attempts. Without this re-registration, after handling the first connection, the server would not accept any more incoming connections, effectively making it a single-connection server.

On the other hand, sockets associated with connected clients (handled by _on_read and _on_write) do not need to accept new connections; instead, they are used for reading from and writing to the respective client. Once a client socket is established, it remains active for the duration of the client-server communication. These sockets are registered for reading or writing depending on the current need (reading data from the client or sending data to the client). They do not need to be re-registered for accepting connections because that is not their role.

Hope that answers your question :)
